### PR TITLE
Fix feature_names getter in SequentialFeatureExtractor

### PR DESCRIPTION
**Pull request by Hakuyume**

### CODE REVIEW

**Comment by yuyu2172** [comment]
How about setting `_return_tuple` and `_feature_names` directly in `__init__`?
~~You can remove line 85~88.~~

**Comment by yuyu2172** [comment]
Nevermind, I think the current code looks OK.

I was confused first when I saw `__getattr__` because it used attributes that seemed to not have been initialized anywhere.
Perhaps it would be better to add a comment in `__init__`.

**Comment by yuyu2172** [comment]
https://github.com/Hakuyume/chainercv/blob/9a3fdeec72204e45b3c688a23b69920fb7bc30ed/chainercv/links/model/sequential_feature_extractor.py#L56

How about adding a comment saying
`_feature_names` and `_return_tuple` are initialized as None

**Comment by Hakuyume** [comment]
> it used attributes that seemed to not have been initialized anywhere.

Your original code also initializes attributes via setter.
https://github.com/yuyu2172/chainercv/blob/1cad17bfb5c32d19058af4020123289779b5fa70/chainercv/links/model/sequential_feature_extractor.py#L66

I added a comment.

**Comment by yuyu2172** [comment]
LGTM

**Comment by yuyu2172** [comment]
I haven't told you clearly, but could you move the comments before `self.feature_names = None`?
Other than that LGTM

**Comment by yuyu2172** [comment]
> Your original code also initializes attributes via setter.
https://github.com/yuyu2172/chainercv/blob/1cad17bfb5c32d19058af4020123289779b5fa70/chainercv/links/model/sequential_feature_extractor.py#L66

It didn't bugged me because those attributes were not used in the getter of feature_names.

**Pull request merged**
